---
title: "Linear Regression for education, airquality dataset"
author: "Dolores Zurdo Consuegra"
date: "08/25/2014"
output: ioslides_presentation
runtime: shiny
---

## About the app

The objective of the app is to show students how linear regression works. They will learn using the app that the perfect linear fit is the line that minimises the Root Mean Square Error (RMSE). Also they see a graphical representation of the Linear Regression problem.

location: http://doloreszurdo.shinyapps.io/airqualityApp/

## arqualityApp inputs

The student can select the predictor variable that he wants to use to predict the level of ozone in the atmosphere. The "Regression Variable" drop-down menu has three options: solar.R, wind or Temp.

Then, using two sliders he can try different linear regression curves (in red) and compare them to the ideal least squares fit (shown in blue). One of the sliders modifies the intercept of the line, and the other the slope of the regression line.

## arqualityApp outputs

The apps shows a plot with the data points belonging to the airquality dataset that relate the ozone level with the selected predictor variable. In the same plot, the line that is obtained using the intercept and slope specified by the user is shown in red, and the perfect regression line (obtained by least squares) is shown in blue.

Below the plot, a text box displays the current Root Mean Squared Error that the red line has with respect to the data points.

## arqualityApp sample graphical output


```{r, echo=FALSE}
rm( list=ls() )
library(shiny)
library(datasets)
data(airquality)
airquality <- airquality[1:4]
for (i in 1:4)
  airquality <- airquality[ !is.na(airquality[[i]]), ]

selected_regvar <- "Solar.R" 

x <- airquality[[selected_regvar]]
y <- airquality[["Ozone"]]
intercept <- 0.0
slope <-     1.0
ypred <- intercept + slope*x
RMSE  <- sqrt( sum( (y-ypred)^2 ) )

formula <- paste(c("Ozone ~ ", selected_regvar), collapse="")
plot_data <- airquality[, c(selected_regvar, "Ozone")]
plot(plot_data, main=formula)
abline(a=intercept, b=slope, col="red", lwd=3)
perfect_fit <- lm( formula, data=airquality)
abline(perfect_fit, col="blue", lwd=3)
legend("topright", c(formula, "selected reg line", "perfect reg line"), pch = c(1,NA_integer_,NA_integer_), lty=c(0,1,1), lwd=c(1,3,3), col=c("black","red","blue") )


paste("(selected reg line) current RMSE:", 1434.7,collapse="")
```